# Generated by Django 5.0.3 on 2024-10-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_alter_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('office', 'Office'), ('quality lab', 'Quality Lab'), ('bulding', 'Building'), ('production Line #1', 'Production Line #1'), ('production Line #2', 'Production Line #2'), ('production Line #3', 'Production Line #3'), ('assembly', 'Assembly'), ('roof', 'Roof')], default='office', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannually', 'Biannually'), ('yearly', 'Yearly')], default='once', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorderrecord',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='records'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
