# Generated by Django 5.0.3 on 2024-10-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0009_alter_asset_location_alter_workorder_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='notification',
            field=models.CharField(choices=[('none', 'None'), ('day before', 'Day Before'), ('week before', 'Week Before'), ('month before', 'Month Before')], default='none', max_length=20),
        ),
    ]
