# Generated by Django 5.0.3 on 2024-10-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0011_alter_workorder_recurrence_checklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='recurrence',
            field=models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Biannually', 'Biannually'), ('Yearly', 'Yearly')], default='Once', max_length=20),
        ),
    ]
