# Generated by Django 5.0.3 on 2024-10-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_alter_workorder_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('flag', 'Flag')], max_length=6, null=True),
        ),
    ]
