# Generated by Django 5.0.3 on 2024-10-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0013_alter_checklistitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='workorder_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='workorder.workorderrecord'),
        ),
    ]
