# Generated by Django 5.0.3 on 2024-11-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0015_alter_workorder_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='recurrence',
            field=models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Biannually', 'Biannually'), ('Yearly', 'Yearly'), ('3 Years', '3 Years')], default='Once', max_length=20),
        ),
    ]
