# Generated by Django 5.0.3 on 2024-11-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0016_alter_workorder_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchased', models.BooleanField(default=False)),
                ('workorder_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_parts', to='workorder.workorderrecord')),
            ],
        ),
    ]
