# Generated by Django 5.0.3 on 2024-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0017_purchasepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepart',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
