# Generated by Django 5.0.3 on 2024-11-07 22:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0018_purchasepart_eta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdItemStd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pph', models.IntegerField()),
                ('people_inline', models.IntegerField()),
                ('setup_time', models.DurationField()),
                ('setup_time_people', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('qty_produced', models.IntegerField(blank=True, null=True)),
                ('produced_in_time', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('people_inline', models.IntegerField(blank=True, null=True)),
                ('setup_time', models.DurationField(blank=True, null=True)),
                ('setup_time_people', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.proditemstd')),
            ],
        ),
    ]
