# Generated by Django 5.0.3 on 2024-11-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0019_proditemstd_proditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='proditem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
