# Generated by Django 5.0.3 on 2024-11-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0021_remove_proditem_produced_in_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proditem',
            name='description',
        ),
        migrations.AddField(
            model_name='proditem',
            name='set_up_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
