# Generated by Django 5.0.3 on 2024-11-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0023_remove_proditem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proditem',
            name='set_up_time',
        ),
        migrations.AlterField(
            model_name='proditem',
            name='produced_in_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proditem',
            name='setup_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
