# Generated by Django 5.0.3 on 2024-11-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0024_remove_proditem_set_up_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proditemstd',
            name='setup_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
