# Generated by Django 5.0.3 on 2024-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0026_dayproductivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayproductivity',
            name='earned_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayproductivity',
            name='extra_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayproductivity',
            name='people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dayproductivity',
            name='total_produced',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
