# Generated by Django 5.0.3 on 2024-11-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0027_alter_dayproductivity_earned_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proditemstd',
            old_name='setup_time_people',
            new_name='setup_people',
        ),
    ]
