# Generated by Django 5.0.3 on 2024-11-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0028_rename_setup_time_people_proditemstd_setup_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proditem',
            old_name='produced_in_time',
            new_name='produced_time',
        ),
        migrations.RenameField(
            model_name='proditem',
            old_name='setup_time_people',
            new_name='setup_people',
        ),
    ]
