# Generated by Django 5.0.3 on 2024-11-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0029_rename_produced_in_time_proditem_produced_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proditemstd',
            name='kind',
            field=models.CharField(choices=[('tube', 'Tube'), ('foil', 'Foil'), ('bottle', 'Bottle'), ('replenishment', 'Replenishment')], default='bottle', max_length=20),
        ),
    ]
