# Generated by Django 5.0.3 on 2024-11-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0030_proditemstd_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proditem',
            name='people_inline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proditemstd',
            name='people_inline',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
