# Generated by Django 5.0.3 on 2024-11-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0032_dayproductivity_total_pieces_bottle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proditemstd',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prod_item_images/'),
        ),
    ]
