# Generated by Django 5.0.3 on 2024-11-22 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0037_rename_productivity_bottle_dayproductivity_bottle_productivity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayproductivity',
            old_name='bottle_productivity',
            new_name='productivity_bottle',
        ),
        migrations.RenameField(
            model_name='dayproductivity',
            old_name='foil_productivity',
            new_name='productivity_foil',
        ),
        migrations.RenameField(
            model_name='dayproductivity',
            old_name='replenishment_productivity',
            new_name='productivity_replenishment',
        ),
        migrations.RenameField(
            model_name='dayproductivity',
            old_name='tube_productivity',
            new_name='productivity_tube',
        ),
        migrations.RenameField(
            model_name='dayproductivity',
            old_name='total_pieces_bottle',
            new_name='total_produced_bottle',
        ),
        migrations.RenameField(
            model_name='dayproductivity',
            old_name='total_pieces_foil',
            new_name='total_produced_foil',
        ),
        migrations.RenameField(
            model_name='dayproductivity',
            old_name='total_pieces_replenishment',
            new_name='total_produced_replenishment',
        ),
        migrations.RenameField(
            model_name='dayproductivity',
            old_name='total_pieces_tube',
            new_name='total_produced_tube',
        ),
    ]
