# Generated by Django 5.0.3 on 2025-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0039_proditemstd_formula_proditemstd_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayproductivity',
            name='productivity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
