# Generated by Django 5.1.5 on 2025-03-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0040_alter_dayproductivity_productivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
