# Generated by Django 5.1.5 on 2025-03-07 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0041_checklistitem_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='records')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('workorder_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_items', to='workorder.workorderrecord')),
            ],
        ),
    ]
