# Generated by Django 5.1.5 on 2025-03-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0042_completeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedItem',
        ),
    ]
