# Generated by Django 5.1.5 on 2025-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0044_rename_purchased_purchasepart_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='proditemstd',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
