# Generated by Django 5.1.5 on 2025-03-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0045_proditemstd_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proditemstd',
            name='points',
        ),
    ]
