# Generated by Django 5.1.5 on 2025-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0046_remove_proditemstd_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='lockout',
            field=models.BooleanField(default=True),
        ),
    ]
