# Generated by Django 5.0.3 on 2024-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_supervisor'),
    ]

    operations = [
        
    ]
